INFO:    Using cached SIF image
[hx1-d10-gpu-05:696225] shmem: mmap: an error occurred while determining whether or not /var/tmp/pbs.172134.pbs-6/ompi.hx1-d10-gpu-05.1327033/jf.0/2002845696/shared_mem_cuda_pool.hx1-d10-gpu-05 could be created.
[hx1-d10-gpu-05:696225] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
mkdir -p failed for path /gpfs/home/jl24018/.config/matplotlib: [Errno 30] Read-only file system: '/gpfs/home/jl24018/.config'
Matplotlib created a temporary cache directory at /var/tmp/pbs.172134.pbs-6/matplotlib-55iyt256 because there was an issue with the default path (/gpfs/home/jl24018/.config/matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Fontconfig error: No writable cache directories
2024-12-22 18:38:23,638 - pymbar.timeseries - WARNING - Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.
2024-12-22 18:38:26,312 - pymbar.mbar_solvers - WARNING - 
****** PyMBAR will use 64-bit JAX! *******
* JAX is currently set to 32-bit bitsize *
* which is its default.                  *
*                                        *
* PyMBAR requires 64-bit mode and WILL   *
* enable JAX's 64-bit mode when called.  *
*                                        *
* This MAY cause problems with other     *
* Uses of JAX in the same code.          *
******************************************

2024-12-22 18:38:26,326 - pymbar.mbar_solvers - INFO - JAX detected. Using JAX acceleration.
2024-12-22 18:38:36,870 - MDAnalysis.core.universe - INFO - The attribute(s) masses, types have already been read from the topology file. The guesser will only guess empty values for this attribute, if any exists. To overwrite it by completely guessed values, you can pass the attribute to the force_guess parameter instead of the to_guess one
2024-12-22 18:38:36,876 - MDAnalysis.guesser.base - INFO - There is no empty types values. Guesser did not guess any new values for types attribute
2024-12-22 18:38:36,878 - MDAnalysis.guesser.base - INFO - There is no empty masses values. Guesser did not guess any new values for masses attribute
2024-12-22 18:38:36,928 - root - INFO - Output directory: /gpfs/home/jl24018/projects/openmm-md/data/241010_FoldingUponBinding/output/CD28-G/241222-LongCMAP
2024-12-22 18:38:36,928 - root - INFO - Input PDB file is equilibrated, assuming it comes from a previous run...
2024-12-22 18:38:36,928 - root - INFO - Copying fixed, equilibrated and solvated pdb files to output directory
2024-12-22 18:38:36,931 - root - WARNING - File /gpfs/home/jl24018/projects/openmm-md/data/241010_FoldingUponBinding/output/CD28-G/241222-LongCMAP/CD28_general_fixed.pdb is the same as the one in the output directory, skipping copy... You are likely doing something manually. Be careful!
2024-12-22 18:38:36,932 - root - WARNING - File /gpfs/home/jl24018/projects/openmm-md/data/241010_FoldingUponBinding/output/CD28-G/241222-LongCMAP/CD28_general_equilibrated.cif is the same as the one in the output directory, skipping copy... You are likely doing something manually. Be careful!
2024-12-22 18:38:36,934 - root - WARNING - File /gpfs/home/jl24018/projects/openmm-md/data/241010_FoldingUponBinding/output/CD28-G/241222-LongCMAP/CD28_general_solvated.cif is the same as the one in the output directory, skipping copy... You are likely doing something manually. Be careful!
2024-12-22 18:38:36,934 - root - INFO - ==================== Running CD28_general ====================
2024-12-22 18:38:36,934 - root - INFO - Running with timestep 2 fs and mdtime 1000 ns
2024-12-22 18:38:36,934 - root - INFO - Bias factor 48 for MetaD
2024-12-22 18:38:36,935 - root - INFO - CV1: cmap with config['cv1.sigma']=0.15
2024-12-22 18:38:36,935 - root - INFO - CV2: d with config['cv2.sigma']=0.27
2024-12-22 18:38:36,935 - src.plumed.opes - INFO - Equilibrated state found at /gpfs/home/jl24018/projects/openmm-md/data/241010_FoldingUponBinding/output/CD28-G/241222-LongCMAP/CD28_general_equilibrated.cif
2024-12-22 18:38:36,935 - src.plumed.opes - INFO - Skipping equilibration...
2024-12-22 18:38:43,831 - src.plumed.opes - INFO - Building system...
2024-12-22 18:38:47,832 - src.utils - INFO - Using CUDA device 0
2024-12-22 18:38:47,832 - src.utils - INFO - Platform used: CUDA with properties {'DeviceIndex': '0', 'Precision': 'mixed'}
2024-12-22 18:38:50,832 - src.plumed.opes - INFO - Box Vectors (in nanometers):
2024-12-22 18:38:50,832 - src.plumed.opes - INFO - x: Vec3(x=14.0, y=0.0, z=0.0)
2024-12-22 18:38:50,832 - src.plumed.opes - INFO - y: Vec3(x=0.0, y=14.0, z=0.0)
2024-12-22 18:38:50,832 - src.plumed.opes - INFO - z: Vec3(x=0.0, y=0.0, z=14.0)
2024-12-22 18:38:51,231 - src.plumed.opes - INFO - PLUMED input file /gpfs/home/jl24018/projects/openmm-md/data/241010_FoldingUponBinding/output/CD28-G/241222-LongCMAP/CD28_general_plumed.dat found, skipping generation. Possibly a manual overwrite.
Traceback (most recent call last):
  File "/gpfs/home/jl24018/projects/openmm-md/scripts/241216_NewCMAP_FuB/run.py", line 114, in <module>
    fire.Fire(run)
  File "/opt/conda/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/jl24018/projects/openmm-md/scripts/241216_NewCMAP_FuB/run.py", line 93, in run
    main(
  File "/gpfs/home/jl24018/projects/openmm-md/src/plumed/main.py", line 288, in main
    run_plumed(
  File "/gpfs/home/jl24018/projects/openmm-md/src/plumed/opes.py", line 238, in run_plumed
    simulation.context.reinitialize(preserveState=True)
  File "/opt/conda/lib/python3.12/site-packages/openmm/openmm.py", line 15415, in reinitialize
    return _openmm.Context_reinitialize(self, preserveState)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: 
(core/Action.cpp:309) void PLMD::Action::error(const std::string&) const
ERROR in input to action CONTACTMAP with label cmap : problem reading SWITCH keyword : could not parse MM
